const cards = [
    {
        id: 1, date: 'March 5, 2024', image: 'https://fastly.picsum.photos/id/10/2500/1667.jpg?hmac=J04WWC_ebchx3WwzbM-Z4_KC_LeLBWr5LZMaAkWkF68', readTime: '5 min read', alt: 'card_1',
        title: 'Turning Dreams into Achievable Targets',
        description: 'Discuss how virtual reality is revolutionizing the way potential buyers explore',
        introduction: 'Mi tincidunt elit, id quisque ligula ac diam, amet. Vel etiam suspendisse morbi eleifend faucibus eget vestibulum felis. Dictum quis montes, sit sit. Tellus aliquam enim urna, etiam. Mauris posuere vulputate arcu amet, vitae nisi, tellus tincidunt. At feugiat sapien varius id.',
        quote: '"Ipsum sit mattis nulla quam nulla. Gravida id gravida ac enim mauris id. Non pellentesque congue eget consectetur turpis. Sapien, dictum molestie sem tempor. Diam elit, orci, tincidunt aenean tempus."',
        conclusion: "Industrial",
        tags: ['Resources', 'Articles'],
    },
    {
        id: 2, date: 'March 5, 2023', image: 'https://fastly.picsum.photos/id/10/2500/1667.jpg?hmac=J04WWC_ebchx3WwzbM-Z4_KC_LeLBWr5LZMaAkWkF68', readTime: '5 min read', alt: 'card_2',
        title: 'How to Start a Side Business While Working Full-Time',
        description: 'Discuss how virtual reality is revolutionizing the way potential buyers explore',
        introduction: 'Mi tincidunt elit, id quisque ligula ac diam, amet. Vel etiam suspendisse morbi eleifend faucibus eget vestibulum felis. Dictum quis montes, sit sit. Tellus aliquam enim urna, etiam. Mauris posuere vulputate arcu amet, vitae nisi, tellus tincidunt. At feugiat sapien varius id.',
        quote: '"Ipsum sit mattis nulla quam nulla. Gravida id gravida ac enim mauris id. Non pellentesque congue eget consectetur turpis. Sapien, dictum molestie sem tempor. Diam elit, orci, tincidunt aenean tempus."',
        conclusion: "Industrial",
        tags: ['Resources'],
    },
    {
        id: 3, date: 'March 5, 2024', image: 'https://fastly.picsum.photos/id/10/2500/1667.jpg?hmac=J04WWC_ebchx3WwzbM-Z4_KC_LeLBWr5LZMaAkWkF68', readTime: '5 min read', alt: 'card_3',
        title: 'Strategies for Overcoming Creative Blocks',
        description: 'Discuss how virtual reality is revolutionizing the way potential buyers explore',
        introduction: 'Mi tincidunt elit, id quisque ligula ac diam, amet. Vel etiam suspendisse morbi eleifend faucibus eget vestibulum felis. Dictum quis montes, sit sit. Tellus aliquam enim urna, etiam. Mauris posuere vulputate arcu amet, vitae nisi, tellus tincidunt. At feugiat sapien varius id.',
        quote: '"Ipsum sit mattis nulla quam nulla. Gravida id gravida ac enim mauris id. Non pellentesque congue eget consectetur turpis. Sapien, dictum molestie sem tempor. Diam elit, orci, tincidunt aenean tempus."',
        conclusion: "Industrial",
        tags: ['Resources'],
    },
    {
        id: 4, date: 'March 5, 2024', image: 'https://fastly.picsum.photos/id/10/2500/1667.jpg?hmac=J04WWC_ebchx3WwzbM-Z4_KC_LeLBWr5LZMaAkWkF68', readTime: '5 min read', alt: 'card_4',
        title: 'Building Stronger Connections',
        description: 'Discuss how virtual reality is revolutionizing the way potential buyers explore',
        introduction: 'Mi tincidunt elit, id quisque ligula ac diam, amet. Vel etiam suspendisse morbi eleifend faucibus eget vestibulum felis. Dictum quis montes, sit sit. Tellus aliquam enim urna, etiam. Mauris posuere vulputate arcu amet, vitae nisi, tellus tincidunt. At feugiat sapien varius id.',
        quote: '"Ipsum sit mattis nulla quam nulla. Gravida id gravida ac enim mauris id. Non pellentesque congue eget consectetur turpis. Sapien, dictum molestie sem tempor. Diam elit, orci, tincidunt aenean tempus."',
        conclusion: "Industrial",
        tags: ['Articles'],
    },
    {
        id: 5, date: 'March 5, 2024', image: 'https://fastly.picsum.photos/id/10/2500/1667.jpg?hmac=J04WWC_ebchx3WwzbM-Z4_KC_LeLBWr5LZMaAkWkF68', readTime: '5 min read', alt: 'card_5',
        title: 'Financial Fitness 101 A Guide to Budgeting and Saving',
        description: 'Discuss how virtual reality is revolutionizing the way potential buyers explore',
        introduction: 'Mi tincidunt elit, id quisque ligula ac diam, amet. Vel etiam suspendisse morbi eleifend faucibus eget vestibulum felis. Dictum quis montes, sit sit. Tellus aliquam enim urna, etiam. Mauris posuere vulputate arcu amet, vitae nisi, tellus tincidunt. At feugiat sapien varius id.',
        quote: '"Ipsum sit mattis nulla quam nulla. Gravida id gravida ac enim mauris id. Non pellentesque congue eget consectetur turpis. Sapien, dictum molestie sem tempor. Diam elit, orci, tincidunt aenean tempus."',
        conclusion: "Industrial",
        tags: ['Articles'],
    },
    {
        id: 6, date: 'March 5, 2024', image: 'https://fastly.picsum.photos/id/10/2500/1667.jpg?hmac=J04WWC_ebchx3WwzbM-Z4_KC_LeLBWr5LZMaAkWkF68', readTime: '5 min read', alt: 'card_6',
        title: 'Simplify Your Life, Amplify Your Joy',
        description: 'Discuss how virtual reality is revolutionizing the way potential buyers explore',
        introduction: 'Mi tincidunt elit, id quisque ligula ac diam, amet. Vel etiam suspendisse morbi eleifend faucibus eget vestibulum felis. Dictum quis montes, sit sit. Tellus aliquam enim urna, etiam. Mauris posuere vulputate arcu amet, vitae nisi, tellus tincidunt. At feugiat sapien varius id.',
        quote: '"Ipsum sit mattis nulla quam nulla. Gravida id gravida ac enim mauris id. Non pellentesque congue eget consectetur turpis. Sapien, dictum molestie sem tempor. Diam elit, orci, tincidunt aenean tempus."',
        conclusion: "Industrial",
        tags: ['News'],
    },
    {
        id: 7, date: 'March 5, 2024', image: 'https://fastly.picsum.photos/id/10/2500/1667.jpg?hmac=J04WWC_ebchx3WwzbM-Z4_KC_LeLBWr5LZMaAkWkF68', readTime: '5 min read', alt: 'card_7',
        title: 'Luxury Real Estate Beyond the Price Tag',
        description: 'Discuss how virtual reality is revolutionizing the way potential buyers explore',
        introduction: 'Mi tincidunt elit, id quisque ligula ac diam, amet. Vel etiam suspendisse morbi eleifend faucibus eget vestibulum felis. Dictum quis montes, sit sit. Tellus aliquam enim urna, etiam. Mauris posuere vulputate arcu amet, vitae nisi, tellus tincidunt. At feugiat sapien varius id.',
        quote: '"Ipsum sit mattis nulla quam nulla. Gravida id gravida ac enim mauris id. Non pellentesque congue eget consectetur turpis. Sapien, dictum molestie sem tempor. Diam elit, orci, tincidunt aenean tempus."',
        conclusion: "Industrial",
        tags: ['Articles'],
    },
    {
        id: 8, date: 'March 5, 2024', image: 'https://fastly.picsum.photos/id/10/2500/1667.jpg?hmac=J04WWC_ebchx3WwzbM-Z4_KC_LeLBWr5LZMaAkWkF68', readTime: '5 min read', alt: 'card_8',
        title: 'Creative Storage Solutions for Small Spaces',
        description: 'Discuss how virtual reality is revolutionizing the way potential buyers explore',
        introduction: 'Mi tincidunt elit, id quisque ligula ac diam, amet. Vel etiam suspendisse morbi eleifend faucibus eget vestibulum felis. Dictum quis montes, sit sit. Tellus aliquam enim urna, etiam. Mauris posuere vulputate arcu amet, vitae nisi, tellus tincidunt. At feugiat sapien varius id.',
        quote: '"Ipsum sit mattis nulla quam nulla. Gravida id gravida ac enim mauris id. Non pellentesque congue eget consectetur turpis. Sapien, dictum molestie sem tempor. Diam elit, orci, tincidunt aenean tempus."',
        conclusion: "Industrial",
        tags: ['Resources'],
    },
    {
        id: 9, date: 'March 5, 2024', image: 'https://fastly.picsum.photos/id/10/2500/1667.jpg?hmac=J04WWC_ebchx3WwzbM-Z4_KC_LeLBWr5LZMaAkWkF68', readTime: '5 min read', alt: 'card_9',
        title: 'Turning Dreams into Achievable Targets',
        description: 'Discuss how virtual reality is revolutionizing the way potential buyers explore',
        introduction: 'Mi tincidunt elit, id quisque ligula ac diam, amet. Vel etiam suspendisse morbi eleifend faucibus eget vestibulum felis. Dictum quis montes, sit sit. Tellus aliquam enim urna, etiam. Mauris posuere vulputate arcu amet, vitae nisi, tellus tincidunt. At feugiat sapien varius id.',
        quote: '"Ipsum sit mattis nulla quam nulla. Gravida id gravida ac enim mauris id. Non pellentesque congue eget consectetur turpis. Sapien, dictum molestie sem tempor. Diam elit, orci, tincidunt aenean tempus."',
        conclusion: "Industrial",
        tags: ['News'],
    },
    {
        id: 10, date: 'March 5, 2024', image: 'https://fastly.picsum.photos/id/10/2500/1667.jpg?hmac=J04WWC_ebchx3WwzbM-Z4_KC_LeLBWr5LZMaAkWkF68', readTime: '5 min read', alt: 'card_10',
        title: 'Neighborhood Spotlight AirEstates Through the Ages',
        description: 'Discuss how virtual reality is revolutionizing the way potential buyers explore',
        introduction: 'Mi tincidunt elit, id quisque ligula ac diam, amet. Vel etiam suspendisse morbi eleifend faucibus eget vestibulum felis. Dictum quis montes, sit sit. Tellus aliquam enim urna, etiam. Mauris posuere vulputate arcu amet, vitae nisi, tellus tincidunt. At feugiat sapien varius id.',
        quote: '"Ipsum sit mattis nulla quam nulla. Gravida id gravida ac enim mauris id. Non pellentesque congue eget consectetur turpis. Sapien, dictum molestie sem tempor. Diam elit, orci, tincidunt aenean tempus."',
        conclusion: "Industrial",
        tags: ['Resources', 'Articles'],
    },
    {
        id: 11, date: 'March 5, 2024', image: 'https://fastly.picsum.photos/id/10/2500/1667.jpg?hmac=J04WWC_ebchx3WwzbM-Z4_KC_LeLBWr5LZMaAkWkF68', readTime: '5 min read', alt: 'card_11',
        title: 'Neighborhood Spotlight AirEstates Through the Ages',
        description: 'Discuss how virtual reality is revolutionizing the way potential buyers explore',
        introduction: 'Mi tincidunt elit, id quisque ligula ac diam, amet. Vel etiam suspendisse morbi eleifend faucibus eget vestibulum felis. Dictum quis montes, sit sit. Tellus aliquam enim urna, etiam. Mauris posuere vulputate arcu amet, vitae nisi, tellus tincidunt. At feugiat sapien varius id.',
        quote: '"Ipsum sit mattis nulla quam nulla. Gravida id gravida ac enim mauris id. Non pellentesque congue eget consectetur turpis. Sapien, dictum molestie sem tempor. Diam elit, orci, tincidunt aenean tempus."',
        conclusion: "Industrial",
        tags: ['Resources', 'Articles'],
    },
    {
        id: 12, date: 'March 5, 2024', image: 'https://fastly.picsum.photos/id/10/2500/1667.jpg?hmac=J04WWC_ebchx3WwzbM-Z4_KC_LeLBWr5LZMaAkWkF68', readTime: '5 min read', alt: 'card_12',
        title: 'Neighborhood Spotlight AirEstates Through the Ages',
        description: 'Discuss how virtual reality is revolutionizing the way potential buyers explore',
        introduction: 'Mi tincidunt elit, id quisque ligula ac diam, amet. Vel etiam suspendisse morbi eleifend faucibus eget vestibulum felis. Dictum quis montes, sit sit. Tellus aliquam enim urna, etiam. Mauris posuere vulputate arcu amet, vitae nisi, tellus tincidunt. At feugiat sapien varius id.',
        quote: '"Ipsum sit mattis nulla quam nulla. Gravida id gravida ac enim mauris id. Non pellentesque congue eget consectetur turpis. Sapien, dictum molestie sem tempor. Diam elit, orci, tincidunt aenean tempus."',
        conclusion: "Industrial",
        tags: ['Resources', 'Articles'],
    },
    {
        id: 13, date: 'March 5, 2024', image: 'https://fastly.picsum.photos/id/10/2500/1667.jpg?hmac=J04WWC_ebchx3WwzbM-Z4_KC_LeLBWr5LZMaAkWkF68', readTime: '5 min read', alt: 'card_13',
        title: 'Neighborhood Spotlight AirEstates Through the Ages',
        description: 'Discuss how virtual reality is revolutionizing the way potential buyers explore',
        introduction: 'Mi tincidunt elit, id quisque ligula ac diam, amet. Vel etiam suspendisse morbi eleifend faucibus eget vestibulum felis. Dictum quis montes, sit sit. Tellus aliquam enim urna, etiam. Mauris posuere vulputate arcu amet, vitae nisi, tellus tincidunt. At feugiat sapien varius id.',
        quote: '"Ipsum sit mattis nulla quam nulla. Gravida id gravida ac enim mauris id. Non pellentesque congue eget consectetur turpis. Sapien, dictum molestie sem tempor. Diam elit, orci, tincidunt aenean tempus."',
        conclusion: "Industrial",
        tags: ['Resources', 'Articles'],
    },
    {
        id: 14, date: 'March 5, 2024', image: 'https://fastly.picsum.photos/id/10/2500/1667.jpg?hmac=J04WWC_ebchx3WwzbM-Z4_KC_LeLBWr5LZMaAkWkF68', readTime: '5 min read', alt: 'card_14',
        title: 'Neighborhood Spotlight AirEstates Through the Ages',
        description: 'Discuss how virtual reality is revolutionizing the way potential buyers explore',
        introduction: 'Mi tincidunt elit, id quisque ligula ac diam, amet. Vel etiam suspendisse morbi eleifend faucibus eget vestibulum felis. Dictum quis montes, sit sit. Tellus aliquam enim urna, etiam. Mauris posuere vulputate arcu amet, vitae nisi, tellus tincidunt. At feugiat sapien varius id.',
        quote: '"Ipsum sit mattis nulla quam nulla. Gravida id gravida ac enim mauris id. Non pellentesque congue eget consectetur turpis. Sapien, dictum molestie sem tempor. Diam elit, orci, tincidunt aenean tempus."',
        conclusion: "Industrial",
        tags: ['Resources', 'Articles'],
    },
    {
        id: 15, date: 'March 5, 2024', image: 'https://fastly.picsum.photos/id/10/2500/1667.jpg?hmac=J04WWC_ebchx3WwzbM-Z4_KC_LeLBWr5LZMaAkWkF68', readTime: '5 min read', alt: 'card_15',
        title: 'Neighborhood Spotlight AirEstates Through the Ages',
        description: 'Discuss how virtual reality is revolutionizing the way potential buyers explore',
        introduction: 'Mi tincidunt elit, id quisque ligula ac diam, amet. Vel etiam suspendisse morbi eleifend faucibus eget vestibulum felis. Dictum quis montes, sit sit. Tellus aliquam enim urna, etiam. Mauris posuere vulputate arcu amet, vitae nisi, tellus tincidunt. At feugiat sapien varius id.',
        quote: '"Ipsum sit mattis nulla quam nulla. Gravida id gravida ac enim mauris id. Non pellentesque congue eget consectetur turpis. Sapien, dictum molestie sem tempor. Diam elit, orci, tincidunt aenean tempus."',
        conclusion: "Industrial",
        tags: ['Resources', 'Articles'],
    },
    {
        id: 16, date: 'March 5, 2024', image: 'https://fastly.picsum.photos/id/10/2500/1667.jpg?hmac=J04WWC_ebchx3WwzbM-Z4_KC_LeLBWr5LZMaAkWkF68', readTime: '5 min read', alt: 'card_16',
        title: 'Neighborhood Spotlight AirEstates Through the Ages',
        description: 'Discuss how virtual reality is revolutionizing the way potential buyers explore',
        introduction: 'Mi tincidunt elit, id quisque ligula ac diam, amet. Vel etiam suspendisse morbi eleifend faucibus eget vestibulum felis. Dictum quis montes, sit sit. Tellus aliquam enim urna, etiam. Mauris posuere vulputate arcu amet, vitae nisi, tellus tincidunt. At feugiat sapien varius id.',
        quote: '"Ipsum sit mattis nulla quam nulla. Gravida id gravida ac enim mauris id. Non pellentesque congue eget consectetur turpis. Sapien, dictum molestie sem tempor. Diam elit, orci, tincidunt aenean tempus."',
        conclusion: "Industrial",
        tags: ['Resources', 'Articles'],
    },
    {
        id: 17, date: 'March 5, 2024', image: 'https://fastly.picsum.photos/id/10/2500/1667.jpg?hmac=J04WWC_ebchx3WwzbM-Z4_KC_LeLBWr5LZMaAkWkF68', readTime: '5 min read', alt: 'card_17',
        title: 'Neighborhood Spotlight AirEstates Through the Ages',
        description: 'Discuss how virtual reality is revolutionizing the way potential buyers explore',
        introduction: 'Mi tincidunt elit, id quisque ligula ac diam, amet. Vel etiam suspendisse morbi eleifend faucibus eget vestibulum felis. Dictum quis montes, sit sit. Tellus aliquam enim urna, etiam. Mauris posuere vulputate arcu amet, vitae nisi, tellus tincidunt. At feugiat sapien varius id.',
        quote: '"Ipsum sit mattis nulla quam nulla. Gravida id gravida ac enim mauris id. Non pellentesque congue eget consectetur turpis. Sapien, dictum molestie sem tempor. Diam elit, orci, tincidunt aenean tempus."',
        conclusion: "Industrial",
        tags: ['Resources', 'Articles'],
    },
    {
        id: 18, date: 'March 5, 2024', image: 'https://fastly.picsum.photos/id/10/2500/1667.jpg?hmac=J04WWC_ebchx3WwzbM-Z4_KC_LeLBWr5LZMaAkWkF68', readTime: '5 min read', alt: 'card_18',
        title: 'Neighborhood Spotlight AirEstates Through the Ages',
        description: 'Discuss how virtual reality is revolutionizing the way potential buyers explore',
        introduction: 'Mi tincidunt elit, id quisque ligula ac diam, amet. Vel etiam suspendisse morbi eleifend faucibus eget vestibulum felis. Dictum quis montes, sit sit. Tellus aliquam enim urna, etiam. Mauris posuere vulputate arcu amet, vitae nisi, tellus tincidunt. At feugiat sapien varius id.',
        quote: '"Ipsum sit mattis nulla quam nulla. Gravida id gravida ac enim mauris id. Non pellentesque congue eget consectetur turpis. Sapien, dictum molestie sem tempor. Diam elit, orci, tincidunt aenean tempus."',
        conclusion: "Industrial",
        tags: ['Resources', 'Articles'],
    },

];
export {cards};