const cards = [
    {
        id: 1, location: 'Churchill Walk, London', image: 'https://fastly.picsum.photos/id/10/2500/1667.jpg?hmac=J04WWC_ebchx3WwzbM-Z4_KC_LeLBWr5LZMaAkWkF68', alt: 'card_1',
        description: '3 bedroom detached house for sale',
        price: 2500,
        type: "Industrial",
        prop_type: "sale",
        tags: ['2bed', '1bath', '818sqdr', '5,619sqft', 'lot'],
        available: true,
    },
    {
        id: 2, location: 'Las Vegas', image: 'https://fastly.picsum.photos/id/10/2500/1667.jpg?hmac=J04WWC_ebchx3WwzbM-Z4_KC_LeLBWr5LZMaAkWkF68', alt: 'card_2',
        description: '4 bedroom detached house for sale',
        price: 5000,
        type: "Industrial",
        prop_type: "new listing",
        tags: ['2bed', '1bath', '818sqdr', '5,619sqft', 'lot'],
        available: false,
    },
    {
        id: 3, location: 'United Kingdom', image: 'https://fastly.picsum.photos/id/10/2500/1667.jpg?hmac=J04WWC_ebchx3WwzbM-Z4_KC_LeLBWr5LZMaAkWkF68', alt: 'card_3',
        description: '5 bedroom detached house for sale',
        price: 700,
        type: "Industrial",
        prop_type: "rent",
        tags: ['2bed', '1bath', '818sqdr', '5,619sqft', 'lot'],
        available: true,
    },
    {
        id: 4, location: 'Florida', image: 'https://fastly.picsum.photos/id/10/2500/1667.jpg?hmac=J04WWC_ebchx3WwzbM-Z4_KC_LeLBWr5LZMaAkWkF68', alt: 'card_4',
        description: '6 bedroom detached house for sale',
        price: 9999,
        type: "Industrial",
        prop_type: "sale",
        tags: ['2bed', '1bath', '818sqdr', '5,619sqft', 'lot'],
        available: true,
    },
    {
        id: 5, location: 'London', image: 'https://fastly.picsum.photos/id/10/2500/1667.jpg?hmac=J04WWC_ebchx3WwzbM-Z4_KC_LeLBWr5LZMaAkWkF68', alt: 'card_4',
        description: '6 bedroom detached house for sale',
        price: 3000,
        type: "Commercial",
        prop_type: "sale",
        tags: ['2bed', '1bath', '818sqdr', '5,619sqft', 'lot'],
        available: true,
    },
    {
        id: 6, location: 'Washington D.C', image: 'https://fastly.picsum.photos/id/10/2500/1667.jpg?hmac=J04WWC_ebchx3WwzbM-Z4_KC_LeLBWr5LZMaAkWkF68', alt: 'card_4',
        description: '6 bedroom detached house for sale',
        price: 5505,
        type: "Residential",
        prop_type: "land",
        tags: ['2bed', '1bath', '818sqdr', '5,619sqft', 'lot'],
        available: true,
    },

];
export {cards};